//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delta.CertXplorer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Delta.CertXplorer.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCD-Date decode failed : the date must be 4 or 7 bytes..
        /// </summary>
        internal static string BcdDateDecodeFailed {
            get {
                return ResourceManager.GetString("BcdDateDecodeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find parameter {0}.
        /// </summary>
        internal static string CantFindParameter {
            get {
                return ResourceManager.GetString("CantFindParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t retrieve WMI object &quot;{0}&quot;..
        /// </summary>
        internal static string CantGetWmiObject {
            get {
                return ResourceManager.GetString("CantGetWmiObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string deletion isn&apos;t implemented..
        /// </summary>
        internal static string ConnectionStringDeletionNotImplemented {
            get {
                return ResourceManager.GetString("ConnectionStringDeletionNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database with id {0} already exists..
        /// </summary>
        internal static string DatabaseIdAlreadyExists {
            get {
                return ResourceManager.GetString("DatabaseIdAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key &quot;{0}&quot; in settings file file://{1}..
        /// </summary>
        internal static string DuplicateKeyInSettingsFile {
            get {
                return ResourceManager.GetString("DuplicateKeyInSettingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In memory generated code.
        /// </summary>
        internal static string DynamicAssembly {
            get {
                return ResourceManager.GetString("DynamicAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File file://{0} already exists and can&apos;t be deleted..
        /// </summary>
        internal static string FileAlreadyExistsAndCantBeDeleted {
            get {
                return ResourceManager.GetString("FileAlreadyExistsAndCantBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found: file://{0}.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray scale (lum).
        /// </summary>
        internal static string GrayScaleLum {
            get {
                return ResourceManager.GetString("GrayScaleLum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray scale (moy).
        /// </summary>
        internal static string GrayScaleMoy {
            get {
                return ResourceManager.GetString("GrayScaleMoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity.
        /// </summary>
        internal static string Identity {
            get {
                return ResourceManager.GetString("Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This instance is already added to a service container..
        /// </summary>
        internal static string InstanceAlreadyAddedToServiceContainer {
            get {
                return ResourceManager.GetString("InstanceAlreadyAddedToServiceContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This instance was never added to a service container..
        /// </summary>
        internal static string InstanceNeverAddedToServiceContainer {
            get {
                return ResourceManager.GetString("InstanceNeverAddedToServiceContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ImageFormat: Guid is null and ICodec is null.
        /// </summary>
        internal static string InvalidImageFormatNullGuidNullICodec {
            get {
                return ResourceManager.GetString("InvalidImageFormatNullGuidNullICodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operation: application has already started..
        /// </summary>
        internal static string InvalidOperationAppAlreadyStarted {
            get {
                return ResourceManager.GetString("InvalidOperationAppAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operation: the application type can&apos;t be changed once it has been created..
        /// </summary>
        internal static string InvalidOperationCantChangeApplicationTypeOnceCreated {
            get {
                return ResourceManager.GetString("InvalidOperationCantChangeApplicationTypeOnceCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native call failed ({0})..
        /// </summary>
        internal static string NativeCallFailed {
            get {
                return ResourceManager.GetString("NativeCallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough bytes to detect format..
        /// </summary>
        internal static string NotEnoughBytesToDetectFormat {
            get {
                return ResourceManager.GetString("NotEnoughBytesToDetectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource not found:
        ///Type = {0}
        ///Resource = {1}.
        /// </summary>
        internal static string ResourceNotFoundFromType {
            get {
                return ResourceManager.GetString("ResourceNotFoundFromType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepia.
        /// </summary>
        internal static string Sepia {
            get {
                return ResourceManager.GetString("Sepia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found: file://{0}; default settings will be loaded for store {1}..
        /// </summary>
        internal static string SettingsFileNotFound {
            get {
                return ResourceManager.GetString("SettingsFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to combine paths {0} and {1} into a valid path..
        /// </summary>
        internal static string UnableToCombinePathsIntoValidPath {
            get {
                return ResourceManager.GetString("UnableToCombinePathsIntoValidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find codec for format {0}..
        /// </summary>
        internal static string UnableToFindCodecForFormat {
            get {
                return ResourceManager.GetString("UnableToFindCodecForFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse Xml file {0}..
        /// </summary>
        internal static string UnableToParseXmlFile {
            get {
                return ResourceManager.GetString("UnableToParseXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database type Unknown is not allowed..
        /// </summary>
        internal static string UnknownDatabaseNotAllowed {
            get {
                return ResourceManager.GetString("UnknownDatabaseNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
