//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertToolsPlugin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CertificateMmcTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CertificateMmcTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CertToolsPlugin.CertificateMmcTemplates", typeof(CertificateMmcTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;&lt;MMC_ConsoleFile ConsoleVersion=&quot;3.0&quot; ProgramMode=&quot;Author&quot;&gt;
        ///  &lt;ConsoleFileID&gt;{64BB0DCD-F331-45B7-8A0B-7E6A7C760A99}&lt;/ConsoleFileID&gt;
        ///  &lt;FrameState ShowStatusBar=&quot;true&quot;&gt;
        ///    &lt;WindowPlacement ShowCommand=&quot;SW_SHOWNORMAL&quot;&gt;
        ///      &lt;Point Name=&quot;MinPosition&quot; X=&quot;-1&quot; Y=&quot;-1&quot;/&gt;
        ///      &lt;Point Name=&quot;MaxPosition&quot; X=&quot;-1&quot; Y=&quot;-1&quot;/&gt;
        ///      &lt;Rectangle Name=&quot;NormalPosition&quot; Top=&quot;467&quot; Bottom=&quot;1212&quot; Left=&quot;187&quot; Right=&quot;1447&quot;/&gt;
        ///    &lt;/WindowPlacement&gt;
        ///  &lt;/FrameState&gt;
        ///  &lt;Views&gt;
        ///    &lt;View ID=&quot;2&quot; ScopePaneWid [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MscTemplate {
            get {
                return ResourceManager.GetString("MscTemplate", resourceCulture);
            }
        }
    }
}
